### ISSUE TITLE
Keyboard ?

### ISSUE THREAD

**Issue by xandro0777** [vlang/vab#119]
Wondering if it is possible to invoke the android keyboard?

**Comment by Larpon** [comment]
It is via [JNI](https://github.com/Larpon/jni/tree/master/examples/android/keyboard)

**Comment by Larpon** [comment]
I don't know of any other ways currently. The keyboard handling in sokol is best for hardware keyboards but software keyboards might only work for some on some phone types - but not all so if you you want the full features of the soft input, JNI is the best bet currently.
