### ISSUE TITLE
An example works weirdly.

### ISSUE THREAD

**Issue by km19809** [vlang/vab#239]
**OS:**
 linux, Ubuntu 20.04.5 LTS (WSL 2)
**V version**
 Version 0.3.2 5f33585
**vab doctor**
vab
        Version 0.3.6 166bd68
        Path "/home/minsoo/.vmodules/vab"
        Base files "/home/minsoo/.vmodules/vab/platforms/android"
env
        ANDROID_SDK_ROOT=/home/minsoo/android_sdk
        SDKMANAGER=/home/minsoo/android_sdk/cmdline-tools/latest/bin/sdkmanager
        JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
Java
        JDK
                Version 11.0.16
                Path "/usr/lib/jvm/java-11-openjdk-amd64"
                Keytool "/usr/lib/jvm/java-11-openjdk-amd64/bin/keytool"
Android
        ENV
                sdkmanager "/home/minsoo/android_sdk/cmdline-tools/latest/bin/sdkmanager"
                sdkmanager.version "7.0"
                Managable true
        SDK
                Path "/home/minsoo/android_sdk"
                Writable true
                APIs available ['29']
        NDK
                Version 22.1.7171670
                Path "/home/minsoo/android_sdk/ndk-bundle"
                Side-by-side false
                min API level available 16
                max API level available 30
                arm64-v8a   ['30', '29', '28', '27', '26', '24', '23', '22', '21']
                armeabi-v7a ['30', '29', '28', '27', '26', '24', '23', '22', '21', '19', '18', '17', '16']
                x86         ['30', '29', '28', '27', '26', '24', '23', '22', '21', '19', '18', '17', '16']
                x86_64      ['30', '29', '28', '27', '26', '24', '23', '22', '21']
        Build
                API 29
                Build-tools 26.0.2
        Packaging
                Format apk
                Bundletool "/home/minsoo/.cache/v/android/bundletool.jar"
Product
        Name "V Test App"
        Package ID "io.v.android"
        Output ""
V
        Version 0.3.2 5f33585
        Path "/home/minsoo/v"

        OS: linux, Ubuntu 20.04.5 LTS (WSL 2)
        Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
        CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

        getwd: /home/minsoo/v/examples/flappylearning
        vmodules: /home/minsoo/.vmodules
        vroot: /home/minsoo/v
        vexe: /home/minsoo/v/v
        vexe mtime: 2022-11-08 02:44:00
        is vroot writable: true
        is vmodules writable: true
        V full version: V 0.3.2 5f33585

        Git version: git version 2.25.1
        Git vroot status: 0.3.2-70-g5f33585e-dirty
        .git/config present: true
        thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
**What did you do?**
I built [a flappylearning example](https://github.com/vlang/v/tree/master/examples/flappylearning).
The command that I used is:
`vab --name "FlappyLearning" --icon "assets/img/bird.png" game.v`
I ran it on my android device, running on android 12.
**What did you expect to see?**
I should see, something similar to the desktop version.
![image](https://user-images.githubusercontent.com/20869932/200465652-bd487c7c-5821-4d2e-8ff2-5d65d6a9bf48.png)

**What did you see instead?**
I got a blank, white background.
![image](https://user-images.githubusercontent.com/20869932/200465868-ed90b2a4-4aae-44ab-8692-4c6855c18092.png)

I suspect the behavior of `os.read_apk_asset`, but I have no clue.
I don't even know if it is a vab issue, because I failed to launch the adb on WSL2.

**Comment by Larpon** [comment]
Yes, the flappylearning example has, for some reason, never worked on any of my Android devices either. I haven't had time to really investigate it yet. I suspect it might be a memory issue. Your result is actually the furthest I've ever seen the example go on Android. On my devices it crashes before startup 😄

**Comment by km19809** [comment]
`2048.v`, which does not use assets, worked as expected in the emulator. (I did not try it on my device.)
So I assume that the read_asset is malfunctioning, but I do not know anything about `vab` debugging.
Can you give me advice?

**Comment by Larpon** [comment]
> `2048.v`, which does not use assets, worked as expected in the emulator. (I did not try it on my device.) So I assume that the read_asset is malfunctioning, but I do not know anything about `vab` debugging. Can you give me advice?

I have updated the [docs with a new debugging section](https://github.com/vlang/vab/blob/master/docs/docs.md#debugging) in https://github.com/vlang/vab/pull/246

**Comment by Larpon** [comment]
Should be fixed now 👍🏻

**Comment by km19809** [comment]
![image](https://user-images.githubusercontent.com/20869932/205181504-865cc829-1704-4cb7-a40c-a66b18497d70.png)
It works now. Thank you.
