### ISSUE TITLE
VAB does not detect `adb`

### ISSUE THREAD

**Issue by km19809** [vlang/vab#249]
**OS:**
OS: windows, Microsoft Windows 10 Education v19044 64-bit
**V version**
V 0.3.2 cbe64cb
**vab doctor**
```
vab.android.sdk.root found SDK in hardcoded paths at "C:\Users\km198\AppData\Local\Android\sdk"
vab
        Version 0.3.7 7bd2bc2
        Path "C:\Users\km198\.vmodules\vab"
        Base files "C:\Users\km198\.vmodules\vab\platforms\android"
env
        SDKMANAGER=C:\Users\km198\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager
        JAVA_HOME=C:\Program Files\Microsoft\jdk-17.0.5.8-hotspot\
Java
        JDK
                Version 17.0.5
                Path "C:\Program Files\Microsoft\jdk-17.0.5.8-hotspot"
                Keytool "C:\Program Files\Microsoft\jdk-17.0.5.8-hotspot\bin\keytool.exe"
Android
        ENV
                sdkmanager "C:\Users\km198\AppData\Local\Android\sdk\cmdline-tools\latest\bin\sdkmanager.bat"
                sdkmanager.version "8.0"
                Managable true
        SDK
                Path "C:\Users\km198\AppData\Local\Android\sdk"
                Writable true
                APIs available ['29', '28']
        NDK
                Version 25.1.8937393
                Path "C:\Users\km198\AppData\Local\Android\sdk\ndk"
                Side-by-side true
                min API level available 19
                max API level available 33
                arm64-v8a   ['33', '32', '31', '30', '29', '28', '27', '26', '24', '23', '22', '21']
                armeabi-v7a ['33', '32', '31', '30', '29', '28', '27', '26', '24', '23', '22', '21', '19']
                x86         ['33', '32', '31', '30', '29', '28', '27', '26', '24', '23', '22', '21', '19']
                x86_64      ['33', '32', '31', '30', '29', '28', '27', '26', '24', '23', '22', '21']
        Build
                API 29
                Build-tools 33.0.0
        Packaging
                Format apk
Product
        Name "V Test App"
        Package ID "io.v.android"
        Output ""
V
        Version 0.3.2 cbe64cb
        Path "C:\v"

        OS: windows, Microsoft Windows 10 Education v19044 64-bit
        Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
        CC version: Error: exec failed (CreateProcess) with code 2: 지정된 파일을 찾을 수 없습니다.
         cmd: cc --version

        getwd: C:\v\examples\flappylearning
        vmodules: C:\Users\km198\.vmodules
        vroot: C:\v
        vexe: C:\v\v.exe
        vexe mtime: 2022-12-01 23:31:05
        is vroot writable: true
        is vmodules writable: true
        V full version: V 0.3.2 cbe64cb

        Git version: git version 2.28.0.windows.1
        Git vroot status: weekly.2022.47-32-gcbe64cb5-dirty
        .git/config present: true
        thirdparty/tcc status: thirdparty-windows-amd64 cb89a4fe
```
**What did you do?**
I ran ` C:\Users\km198\.vmodules\vab\vab --api 28 --log --device auto -v -v run game.v`
**What did you expect to see?**
It should detect `adb` as usual and run the app in the emulator.
**What did you see instead?**
```
vab.android.sdk.root found SDK in hardcoded paths at "C:\Users\km198\AppData\Local\Android\sdk"
Notice: Android API level 28 is less than the default level (29).
Compiling V to C
Compiling V import C dependencies (.c to .o for ['arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64']) in parallel
Compiling C output for ['arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'] in parallel
Preparing package "io.v.android"...
Removing previous package directory "C:\Users\km198\AppData\Local\Temp\vab\package\apk"
Copying base files from "C:\Users\km198\.vmodules\vab\platforms\android" to "C:\Users\km198\AppData\Local\Temp\vab\package\apk"
Modifying base files
Copying assets
Including assets from ".\assets"
Including assets from "C:\v\examples\assets"
vab deployment didn't succeed.
vab.android.deploy_apk: Couldn't locate "adb". Please make sure it's installed.
```

**Additional Information**
My `adb` is located at: `C:\Users\km198\AppData\Local\Android\Sdk\platform-tools`
![image](https://user-images.githubusercontent.com/20869932/205182712-3303a8e5-a70e-4ef8-8aaf-5c60d053fdff.png)

If I set the `ADB` environment variable,
 `vab` detects the variable:
```
env
        SDKMANAGER=C:\Users\km198\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager
        ADB=C:\Users\km198\AppData\Local\Android\Sdk\platform-tools\adb
        JAVA_HOME=C:\Program Files\Microsoft\jdk-17.0.5.8-hotspot\
```
but not the executable:
![image](https://user-images.githubusercontent.com/20869932/205183392-19a1c0b1-3ea5-4b8c-9558-203c186a31bf.png)

So I set the variable with the file extension:
![image](https://user-images.githubusercontent.com/20869932/205183631-8b9f6a59-8e87-47e1-833a-da433ca17384.png)
It successfully detects and runs the app.

This is weird because neither `cmd.exe` nor `PowerShell` require `.exe` to run the executable.

**Comment by km19809** [comment]
I found the cause. [`os.is_executable`](https://github.com/vlang/v/blob/1cad7887796847570127eed2058746481f2775c3/vlib/os/os.c.v#L424) was the cause.
Unlike Unix, it checks the file extension in Windows.
However, [`adb`](https://github.com/vlang/vab/blob/9c974b6ff1554243ee7b0932b0eb92d806ef5cd7/android/env/env.v#L658) function joins path with 'adb', not 'adb.exe'
So, the joined path does not have any extension.
As a result, `vab` assumes there is no `adb`.

There are some possible solutions.
1. Fix `os.is_executable`. EXE files start with [MZ](https://en.wikipedia.org/wiki/DOS_MZ_executable) in windows. If we read the first two bytes of a file, we can classify it more accurately. There is [WIN32 API](https://learn.microsoft.com/ko-kr/windows/win32/api/winbase/nf-winbase-getbinarytypea?redirectedfrom=MSDN), too.
2. Use the `dot_exe` approach. It is used in [`aapt2`](https://github.com/vlang/vab/blob/9c974b6ff1554243ee7b0932b0eb92d806ef5cd7/android/env/env.v#L732).

For the `dot_exe` approach, we may define `dot_exe` as const, to use them in `aapt`, `adb`, and `ensure_aapt2`.

What do you think?

**Comment by JalonSolov** [comment]
I would go with the `dot_exe` approach.  Windows itself checks the extension, rather than the file contents, before trying to run the file.

Windows also only checks extensions defined in the `PATHEXT` env var, and it checks in the order shown there.

**Comment by Larpon** [comment]
Ouch, I actually added [this check](https://github.com/vlang/vab/pull/253/files#diff-b55b53fae9bd5973cda43c020fe31405a2d6bcfb4fce9b410b8659c85ff7a3c7R655) recently when I added screenshot support, so it's a regression on Windows. Thanks for reporting this
