### ISSUE TITLE
Feature Request: Answer this in the docs: What works and what doesn't?

### ISSUE THREAD

**Issue by elimisteve** [vlang/vab#265]
Do HTTP requests work? And more broadly, what, if any, gotchas are there when running V on Android versus V on, say, Linux?

Thanks!

**Comment by xandro0777** [comment]
Network should work fine but depends on library that you pick. Expect some extra nuisance for server Apps because of battery optimization.

Last time I looked the UI text input was a very bad hack, did anything improve here?

**Comment by Larpon** [comment]
It's impossible for me to know everything about what works and what doesn't. I don't think it's humanly possible to know, actually. I do know that networking should work as long as you add the right permission for it in your manifest 🙂

Also; all pure V code should run on Android. If you have C dependencies, your milage may vary. If you find something that doesn't work please open a bug report.
